version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    image: verevkinaee/skypro-1:latest
    command: python3 create_tables.py
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  api:
    image: verevkinaee/skypro-1:latest
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: flask run -h 0.0.0.0 -p 80
    ports:
      - ${API_PORT}:80

volumes:
  postgres_data:
